### ISSUE TITLE
Does the module support Check Mode?

### ISSUE THREAD

**Issue by pokepoke81** [CiscoDevNet/ansible-meraki#92]
Looking to see if check mode is supported to see changes before apply:

https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html

**Comment by kbreit** [comment]
@pokepoke81 Which modules are you looking to use check mode on? I have it implemented on only some of them.

**Comment by pokepoke81** [comment]
Right now, I'm using meraki_mx_l3_firewall, meraki_static_route, meraki_vlan, meraki_switch_access_list, and meraki_mx_site_to_site_firewall.

**Comment by kbreit** [comment]
I need to update the settings to email me when there are comments since I didn't see your response. Note, the modules may say in code they support check mode but that may not be true; I need to fix that.

Now...just because I am saying a module supports check mode below doesn't mean it's bug free. I need to mock the response from Meraki so I can't promise the responses you receive in check mode will perfectly match the responses you would receive from Meraki. Please test check mode before using in production (fake network perhaps?) and report any bugs. I've been eager for people to test check mode and am looking forward to hearing about your experience.

* `meraki_mx_l3_firewall` - Supports check mode
* `meraki_static_route` - Supports check mode
* `meraki_vlan` - Supports check mode
* `meraki_switch_access_list` - Supports check mode
* `meraki_mx_site_to_site_firewall` - Supports check mode

If you're content with this response, please close this issue and open subsequent issues if you experience bugs. Thanks.

**Comment by pokepoke81** [comment]
Ok, I added check mode to each of those calls with no ill effects. I tested adding a rule with `meraki_mx_site_to_site_firewall` and the check mode reported changed without changing anything (good news). I'll test the rest of them as I deploy so more code, but all looks good so far.

**Comment by kbreit** [comment]
Thank you. I'm going to close this but if you see any problems, please create new issues.
